### ISSUE TITLE
Montecarlo Sampling Question

### ISSUE THREAD

**Issue by simomagi** [tfjgeorge/nngeometry#32]
Looking at the implementation of the Monte Carlo Sampling for computing the Fisher Information I see that the sampled probabilities are divided by the square root of the number of trials. Is there a specific reason for this? Why not simply dividing by the number of trials?

**Comment by tfjgeorge** [comment]
Hi, if you look at the formula:
![Screenshot from 2021-10-01 15-05-50](https://user-images.githubusercontent.com/1521241/135624542-356e6a91-e13a-411f-8d70-c802de70bb35.png)

To get a 1/n on the left hand side, you need to factorize by 1/sqrt(n) in the parenthesis on the right hand side
