### ISSUE TITLE
An example for gram matrix computation?

### ISSUE THREAD

**Issue by liutianlin0121** [tfjgeorge/nngeometry#4]
Hi,

Thanks for this great resource! The existing example available is about FIM computation. I am wondering if you could also provide an example for computing gram matrix of empirical NTK of a finite-width network (perhaps with a dummy dataloader)? This will be highly helpful. 

Since this is a request, please feel free to close this issue ;-)

Cheers,
Tianlin

**Comment by tfjgeorge** [comment]
Hi, thanks for your interest in NNGeometry!

I just added a quick example of a Gram matrix computation for the CIFAR10 10-class classification task on a ResNet18 model on the following [ipynb notebook](https://github.com/tfjgeorge/nngeometry/blob/master/examples/NNGeometry_Gram_matrix_example.ipynb), or directly as a [colab notebook](https://colab.research.google.com/github/tfjgeorge/nngeometry/blob/master/examples/NNGeometry_Gram_matrix_example.ipynb).

**Comment by liutianlin0121** [comment]
Thanks a lot!
