### ISSUE TITLE
An error encountered when running code

### ISSUE THREAD

**Issue by zcb1729** [tfjgeorge/nngeometry#47]
I'm a rookie in python. When running the exmaple from 
https://github.com/tfjgeorge/nngeometry-examples/blob/main/Gram_matrix_example.ipynb
I recieved an error 
AttributeError: 'Jacobian' object has no attribute 'grads'
and I'm helpless to solve it by myself.
Do you have any ideas to solve this problem?

**Comment by zcb1729** [comment]
I ran the code on another computer with the same environment and it works well...There might be a problem with my computer.

**Comment by tfjgeorge** [comment]
You might have installed an old version of NNGeometry ?

T
