### ISSUE TITLE
matrix visualization

### ISSUE THREAD

**Issue by fmaaf** [tfjgeorge/nngeometry#52]
Hello, thanks for your great work! Would you mind share the matrix visualization(https://nngeometry.readthedocs.io/en/latest/pspace_repr.html) codes? Thanks!

**Comment by tfjgeorge** [comment]
whoops it used to be here: https://github.com/tfjgeorge/nngeometry/blob/a91cb2d72471747087e7ba263106bd42d3fc6d85/examples/Timings%20and%20display%20of%20FIM%20representations.ipynb but it disappeared with next commit.

I put it back here: https://github.com/tfjgeorge/nngeometry-examples/blob/main/display_and_timings/Timings%20and%20display%20of%20FIM%20representations.ipynb
