### ISSUE TITLE
Adding support for Conv1d layers

### ISSUE THREAD

**Issue by Xuzzo** [tfjgeorge/nngeometry#73]
Hello and thanks again for your work.

Would it be possible to add support for Conv1d layers in K-FAC?

Thanks

**Comment by tfjgeorge** [comment]
Hi,
this PR: https://github.com/tfjgeorge/nngeometry/pull/76 should do it.

I also implemented EKFAC if you are interested, it gives a more accurate FIM, at a slightly higher computational cost. It requires an extra call to `M_ekfac.update_diag(loader)` after your FIM is instantiated.

**Comment by Xuzzo** [comment]
Hi, 
thank you very much for the help! Closing the issue.
